# This workflows build script references and adapts logic from:
# - [scripts/build_kernel] by UtsavBalar1231
# - [build.sh] by liyafe1997
# - [.github/workflows/Build_Kernel.yml] by yspbwx2010
# Many thanks to their authors for the inspiration.

name: Build Kernel

on:
  workflow_dispatch:
    inputs:
      target_device:
        description: 'Target device'
        required: true
        default: 'munch'
        type: choice
        options:
          - 'munch'
          - 'lmi'
          - 'umi'
          - 'psyche'
          - 'cmi'
          - 'cas'
          - 'apollo'
          - 'alioth'
          - 'elish'
          - 'enuma'
          - 'dagu'
          - 'pipa'

      system_version:
        description: 'Target System'
        required: true
        type: choice
        default: 'miui'
        options:
          - 'aosp'
          - 'miui'

      kernelsu_version:
        description: 'KernelSU Version'
        required: true
        type: choice
        default: 'noksu'
        options:
          - 'rksu'
          - 'sukisu'
          - 'resukisu'
          - 'noksu'

      enable_kpm:
        description: 'Enable KPM (only SukiSU)'
        required: true
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Kernel Source
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update -y 
          sudo apt-get install -y \
          build-essential git curl wget bison flex zip bc \
          cpio libssl-dev libncurses-dev gcc \
          python3 python3-pip ccache
            
      - name: Cache Proton Clang
        uses: actions/cache@v4
        id: clang-cache
        with:
          path: toolchain/proton-clang
          key: ${{ runner.os }}-proton-clang

      - name: Download Proton Clang Toolchain
        if: steps.clang-cache.outputs.cache-hit != 'true'
        run: |
          git clone --depth=1 https://github.com/kdrag0n/proton-clang.git toolchain/proton-clang
          rm -f toolchain/proton-clang/bin/ld
          
      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ccache_mikernel
          key: ${{ runner.os }}-ccache-${{ github.event.inputs.target_device }}-${{ github.event.inputs.system_version }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Build Kernel
        run: |
          TOOLCHAIN_PATH=$(pwd)/toolchain/proton-clang/bin
          TARGET_DEVICE=${{ github.event.inputs.target_device }}
          export PATH="$TOOLCHAIN_PATH:$PATH"

          # Enable ccache for speed up compiling
          export CCACHE_DIR="$HOME/.cache/ccache_mikernel"
          export PATH="/usr/lib/ccache:$PATH"
          echo "CCACHE_DIR: [$CCACHE_DIR]"

          MAKE_ARGS="ARCH=arm64 \
              SUBARCH=arm64 \
              O=out \
              CC=clang \
              CROSS_COMPILE=aarch64-linux-gnu- \
              CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
              CROSS_COMPILE_COMPAT=arm-linux-gnueabi- \
              CLANG_TRIPLE=aarch64-linux-gnu-"

          if [ ! -f "arch/arm64/configs/${TARGET_DEVICE}_defconfig" ]; then
              echo "No target device [${TARGET_DEVICE}] found."
              echo "Available defconfigs, please choose one target from below:"
              ls arch/arm64/configs/*_defconfig
              exit 1
          fi

          # Initialize variables
          KERNEL_SRC=$(pwd)
          KPM_ENABLE=${{ github.event.inputs.enable_kpm }}
          KSU_VERSION=${{ github.event.inputs.kernelsu_version }}
          TARGET_SYSTEM=${{ github.event.inputs.system_version }}

          KSU_ENABLE=$([[ "$KSU_VERSION" == "rksu" || "$KSU_VERSION" == "sukisu" ]] && echo 1 || echo 0)

          # KernelSU setup
          case "$KSU_VERSION" in
              rksu)
                  KSU_ZIP_STR=RKSU
                  echo "RKSU is enabled"
                  curl -LSs "https://raw.githubusercontent.com/rsuntk/KernelSU/main/kernel/setup.sh" | bash -s main
                  ;;
              sukisu)
                  KSU_ZIP_STR=SukiSU
                  echo "SukiSU is enabled"
                  curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s nongki
                  ;;
            resukisu)
                KSU_ZIP_STR=ReSukiSU
                echo "ReSukiSU is enabled"
                curl -LSs "https://raw.githubusercontent.com/ReSukiSU/ReSukiSU/main/kernel/setup.sh" | bash
                ;;        
              *)
                  KSU_ZIP_STR=NoKernelSU
                  echo "KSU is disabled"
                  ;;
          esac

          git clone https://github.com/liyafe1997/AnyKernel3 -b kona --single-branch --depth=1 anykernel

          Build_AOSP() {
              echo "Building for AOSP......"
              make $MAKE_ARGS ${TARGET_DEVICE}_defconfig
              SET_CONFIG
              make $MAKE_ARGS -j$(nproc)
